### PR TITLE
Fix US server

### PR DESCRIPTION
**Pull request by szymjaw**
This path  fix GuardianConnect for US servers
Checked with US and EU user.

### CODE REVIEW

**Comment by unsoluble** [comment]
What do we need to do to get this merged?

**Review by ghost — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Review by mddub — APPROVED** [review]

**Comment by mddub** [comment]
Just bumped to v1.3.0 and published to npm. Sorry for delay.

**Comment by unsoluble** [comment]
Thanks!

**Comment by szymjaw** [comment]
Thanks

**Comment by PieterGit** [comment]
Version 1.3.1 of minimed-connect-to-nightscout is integrated into Nightscout with https://github.com/nightscout/cgm-remote-monitor/pull/4915 . Please help test that PR.

**Comment by PieterGit** [comment]
This is integrated into Nightscout and will be released with Nightscout 0.12.4. See https://github.com/nightscout/cgm-remote-monitor/pull/4915

**Pull request merged**
