### PR TITLE
Dev v.1.3.2

### PR DESCRIPTION
**Pull request by szymjaw**
MiniMed Connect error: Bad response from CareLink

MiniMed Connect error: Error: Bad response from CareLink: 
data for login should be send in body.
If data for login are in address "https://carelink.minimed.eu/patient/j_security_check?j_username=XXX&j_password=YYY", application send response "Bad Request page".
When the address is 'https://carelink.minimed.eu/patient/j_security_check' and post body =  "j_username=XXX&j_password=YYY" all is ok.
j_character_encoding: "UTF-8" I add becouse careapplication put this in post body.

### CODE REVIEW

**Comment by szymjaw** [comment]
Not working with MMCONNECT_SERVER=„US”

**Comment by szymjaw** [comment]
I'm sorry, but I have set the wrong login details.  now it is working.  I confirm work, also on the US server.

**Comment by mddub** [comment]
¯\_(ツ)_/¯

**Comment by JohnnyB31** [comment]
Do you have a solution for the cgm-remote-monitor as well?

**Comment by maskac** [comment]
JohnnyB31  apply patch manualy, it's work.

**Pull request merged**
